# github runner to run pylint on the repo

# Trigger the workflow on push or pull request
on: 
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
      - name: install_pylint
        run: |
          apt update
          apt -y install python3-pip
          pip3 install pylint

      # - name: install_requirements
      #   run: |
      #     pip install -r requirements*.txt

      - name: lint
        run: |
          pylint .